<?php
/* Do Not Edit This File */
return [
    'key' => env('APP_MASTER', '34185625'),
    'file_size'=>2048,
    'printer'=>'network',
    'captcha' => env('CAPTCHA_SECURITY'),
    'fixed_url' => env('FIXED_URL'),
    'delay' =>1500,
];
